1try
Sirokko25/sheduler pull request #1
Opened 2024-06-30 21:30 UTC by Sirokko25

2024-07-01 09:11 UTC, dirtymew requested changes
Привет Александр

хорошая работа - но пока еще не готово

- нужно добавить документацию по проекту - как запускать/ тестировать/настраивать
- нужно немного отрефакторить - по другому разделить на компоненты
- поправить ошибки

задания со звездочкой будешь делать?

2024-07-01 09:11 UTC, dirtymew commented on main.go
> +	"final/changetask"
что-то с группировкой импортов 

используй go imports - для группировки и сортировки

это во всем проекте

2024-07-01 09:11 UTC, dirtymew commented on main.go
> +	//для 7 задачи
лишние комментарии

2024-07-01 09:11 UTC, dirtymew commented on main.go
> +	database.Createdatabase()
сначала лучше - получить параметры из переменных окружения
потом инициализировать подключение к бд И так далее
затем только http роутер и запуск веб сервера

2024-07-01 09:11 UTC, dirtymew commented on main.go
> +	if err := http.ListenAndServe(":7540", r); err != nil {
до запуска хорошо бы написать в лог что сервис запущен и на каком порту

2024-07-01 09:11 UTC, dirtymew commented on nextdate/nextdate.go
> +func YearsCalculatingdate(nowTime time.Time, dateTime time.Time) (string, error) {
название не очень и не по канону - тогда уже так YearsCalculatingDate
но лучше переназвать

2024-07-01 09:11 UTC, dirtymew commented on nextdate/nextdate.go
> +func Parsingrepeatrules(rule string) ([]string, error) {
ParsingrRepeatRules

а лучше  PasreRepeatRules, ValidateRepeatRules,  GetRepeatRules ...

2024-07-01 09:11 UTC, dirtymew commented on nextdate/nextdate.go
> +func CalcNextDate (now string, date string, repeat string) (string, error){
func CalcNextDate( - используй go fmt

2024-07-01 09:11 UTC, dirtymew commented on addtask/addtask.go
> +package addtask
не очень хорошо разложил хендлеры - лучше в одном пакете handlers

или мб лучше в одном файле handlers.go

2024-07-01 09:11 UTC, dirtymew commented on addtask/addtask.go
> +func checkdate (task task.Task) (task.Task, error) {
это лучше в пакет task и сделать методом структуры Task

2024-07-01 09:11 UTC, dirtymew commented on addtask/addtask.go
> +						task.Date = now.Format("20060102")
20060102 - лучше определить константу и везде ее использовать

2024-07-01 09:11 UTC, dirtymew commented on addtask/addtask.go
> +	db, err := sql.Open("sqlite3", "scheduler.db")
плохо открывать на каждый запрос подлючение к бд

нужно при старте инициализировать одни раз и потом его использовать

для разделения на компоненты https://medium.com/@shershnev/layered-architecture-implementation-in-golang-6318a72c1e10
и
https://github.com/golang-standards/project-layout

мб будет полезно

2024-07-01 09:11 UTC, dirtymew commented on addtask/addtask.go
> +func Addtask(w http.ResponseWriter, r *http.Request) {
лучше по другому разделить на компоненты - хендлеры в одном пакете

а работу с бд отдельно в другом

2024-07-01 09:11 UTC, dirtymew commented on checktask/checktask.go
> +func Checktask(w http.ResponseWriter, r *http.Request){
GetTask ?

2024-07-01 09:11 UTC, dirtymew commented on completedtask/completedtask.go
> +func Completedtask (w http.ResponseWriter, r *http.Request) {
TaskDone?

2024-07-01 09:11 UTC, dirtymew commented on receivetasks/receivetasks.go
> +	rows, err := db.Query(`SELECT id, date, title, comment, repeat FROM scheduler ORDER BY date LIMIT 50`)
лимит в константу лучше вынести

2024-07-07 14:59 UTC, dirtymew requested changes
Привет Александр

дал комментарии что поправить - стало лучше но нужно еще рефакторить

2024-07-07 14:59 UTC, dirtymew commented on nextdate/LogicNextDate.go
> +package nextdate
файл nextdate/LogicNextDate.go назван не в стиле go с большой буквы

да и и само название не очень - лучше просто nextdate.go

2024-07-07 14:59 UTC, dirtymew commented on receivetasks/receivetasks.go
> +func GetRow(db *sql.DB) ([]task.Task, error) {
разьехалсась логика работы с БД по пакетом - это нужно в пакет databese перенести

2024-07-07 14:59 UTC, dirtymew commented on receivetasks/receivetasks.go
> +func GetRow(db *sql.DB) ([]task.Task, error) {
функция плохо называется

мы на выходе получаем коллекцию task.Task а она называет get row - в единственном числе 

в общем назвать лучше GetTasks

2024-07-07 14:59 UTC, dirtymew commented on addtask/LogicAddTask.go
> +func Checkdate(task task.Task) (task.Task, error) {
это лучше все сделать методами структуры Task

2024-07-07 14:59 UTC, dirtymew commented on deletetask/LogicDeleteTask.go
> +package deletetask
это тоже все в database

2024-07-07 14:59 UTC, dirtymew commented on handlers/addtask.go
> +func AddTask(db *sql.DB) http.HandlerFunc {
плохо в хендлер передавать подключение к бд

заведи в пакета database стурктуру и храни подлючение в ней

все функции нужно сделать ее методами - посмотри как в задании про посылки было сделано 

ну и да пакет database лучше переименовать в storage

2024-07-07 14:59 UTC, dirtymew commented on database/execquery.go
> +func ExecQuery(db *sql.DB, task task.Task) string {
очень плохое название для функции - UpdateTask или просто Update

2024-07-08 17:58 UTC, dirtymew requested changes
Привет Александр

уже думал засчитавать)) 

осталось немного мелочи поправить

если будешь делать задания со звездочкой - то самая пора если нет исправляй и будем считать что все готово

2024-07-08 17:58 UTC, dirtymew commented on constant/constant.go
> +	ParseDate = "20060102"
не надо так - лучше их обьявить 

ParseDate - в nextdate
Limit - в storage 

например

2024-07-08 17:58 UTC, dirtymew commented on handlers/handlers.go
> +	Db storage.DB
лучше так 
type Handlers struct {
	taskStorage storage.DB

2024-07-08 17:58 UTC, dirtymew commented on storage/storage.go
> +func (db *DB) Deletetask(id string) string {
зачем 2 метода удаления? одного должно быть достаточно

2024-07-08 20:37 UTC, dirtymew requested changes
Привет Александр


не работают тесты - нужно чтобы работали

если нужны доп настройки то они должны быть в документации

2024-07-08 20:37 UTC, dirtymew commented on handlers/handlers.go
> +const ParseDate = "20060102"
а зачем 2 константы почему одной не хватило? )

2024-07-08 20:43 UTC, Sirokko25 commented on handlers/handlers.go
> +const ParseDate = "20060102"
У меня все тесты проходят на Ubunty
![тесты](https://github.com/Sirokko25/final/assets/147556005/07cd4164-819c-4db8-9619-e556f59d98ed)

2024-07-08 20:51 UTC, dirtymew commented on handlers/handlers.go
> +const ParseDate = "20060102"
мб что-то с переменными окружения у меня ругается на  no such table: scheduler

2024-07-08 20:58 UTC, dirtymew commented on handlers/handlers.go
> +const ParseDate = "20060102"
или что-то с созданием бд мб она локально у тебя лежит поэтому все работает...

2024-07-08 21:08 UTC, dirtymew commented on handlers/handlers.go
> +const ParseDate = "20060102"
@Sirokko25 кажется нашел в чем дело - это использование os.Executable()... 

там на разных системах будет разное поведение

лучше относительными путями пользовать 

```
dbFile := "scheduler.db"
_, err = os.Stat(dbFile)

```

2024-07-08 23:26 UTC, dirtymew approved these changes
Привет Александр

тесты приложение проходит - все отлично, есть нюансы с их запуском, но думаю можно считать что задание выполнено
Поздравляю и желаю удачи

PS прошу прощения опечатался в имени...

2024-07-09 14:38 UTC, merged